FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_DEFAULT_TIMEOUT=1000

WORKDIR /app

COPY requirements/frontend.txt  .

RUN pip install --no-cache-dir -r frontend.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "app/frontend.py", "--server.address=0.0.0.0", "--server.port=8501"]