version: "3.9"

services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped

    ports:
      - "6333:6333"

    volumes:
      - qdrant_storage:/qdrant/storage

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend

    container_name: rag-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - qdrant

    volumes:
      - ./app/data:/app/app/data

    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend

    container_name: rag-frontend

    ports:
      - "8501:8501"

    env_file:
      - .env

    depends_on:
      - backend

    restart: unless-stopped

volumes:
  qdrant_storage: